# Generated by Django 4.1 on 2022-08-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_options_lead_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
