# Generated by Django 4.1 on 2022-08-26 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_userprofile_agent_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='organisation',
        ),
    ]
